In [1]:
import numpy as np, pandas as pd

s = pd.Series(np.arange(1, 10), index=[["a", "a", "a", "b", "b", "c", "c", "d", "d"], [1, 2, 3, 1, 2, 3, 1, 2, 3]])
s

a  1    1
   2    2
   3    3
b  1    4
   2    5
c  3    6
   1    7
d  2    8
   3    9
dtype: int64

In [2]:
s.index

MultiIndex(levels=[['a', 'b', 'c', 'd'], [1, 2, 3]],
           labels=[[0, 0, 0, 1, 1, 2, 2, 3, 3], [0, 1, 2, 0, 1, 2, 0, 1, 2]])

In [3]:
s['a']

1    1
2    2
3    3
dtype: int64

In [4]:
s['b']

1    4
2    5
dtype: int64

In [5]:
s['c']

3    6
1    7
dtype: int64

In [6]:
s['a', 1]

1

In [7]:
s['a', [[1, 3]]]

TypeError: '('a', [[1, 3]])' is an invalid key

In [8]:
s['a'][[1, 3]]

1    1
3    3
dtype: int64

In [9]:
s[['a', 'c']]

a  1    1
   2    2
   3    3
c  3    6
   1    7
dtype: int64

In [10]:
s['b':'d']

b  1    4
   2    5
c  3    6
   1    7
d  2    8
   3    9
dtype: int64

In [11]:
s['b':'d'][[1, 3]]

b  2    5
c  1    7
dtype: int64

In [12]:
s.unstack()
s

a  1    1
   2    2
   3    3
b  1    4
   2    5
c  3    6
   1    7
d  2    8
   3    9
dtype: int64

In [13]:
s1 = s.unstack()
s1

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>1</th>
      <th>2</th>
      <th>3</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>a</th>
      <td>1.0</td>
      <td>2.0</td>
      <td>3.0</td>
    </tr>
    <tr>
      <th>b</th>
      <td>4.0</td>
      <td>5.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>c</th>
      <td>7.0</td>
      <td>NaN</td>
      <td>6.0</td>
    </tr>
    <tr>
      <th>d</th>
      <td>NaN</td>
      <td>8.0</td>
      <td>9.0</td>
    </tr>
  </tbody>
</table>
</div>

In [14]:
score = pd.DataFrame(np.random.randint(0, 100, size=(16, 12)),
                     columns=pd.MultiIndex.from_product([['模拟考', '正式考'],
                                                         ['数学', '语文', '英语', '物理', '化学', '生物']]),
                     index=pd.MultiIndex.from_product([['期中', '期末'],
                                                       ['Steve', 'Jobs', 'Chph', 'CCL'],
                                                       ['测试一', '测试二']]))
score

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead tr th {
        text-align: left;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
      <th colspan="6" halign="left">模拟考</th>
      <th colspan="6" halign="left">正式考</th>
    </tr>
    <tr>
      <th></th>
      <th></th>
      <th></th>
      <th>数学</th>
      <th>语文</th>
      <th>英语</th>
      <th>物理</th>
      <th>化学</th>
      <th>生物</th>
      <th>数学</th>
      <th>语文</th>
      <th>英语</th>
      <th>物理</th>
      <th>化学</th>
      <th>生物</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th rowspan="8" valign="top">期中</th>
      <th rowspan="2" valign="top">Steve</th>
      <th>测试一</th>
      <td>76</td>
      <td>72</td>
      <td>51</td>
      <td>73</td>
      <td>22</td>
      <td>78</td>
      <td>90</td>
      <td>59</td>
      <td>75</td>
      <td>9</td>
      <td>41</td>
      <td>37</td>
    </tr>
    <tr>
      <th>测试二</th>
      <td>5</td>
      <td>82</td>
      <td>47</td>
      <td>95</td>
      <td>89</td>
      <td>21</td>
      <td>1</td>
      <td>37</td>
      <td>85</td>
      <td>34</td>
      <td>59</td>
      <td>33</td>
    </tr>
    <tr>
      <th rowspan="2" valign="top">Jobs</th>
      <th>测试一</th>
      <td>17</td>
      <td>80</td>
      <td>95</td>
      <td>13</td>
      <td>23</td>
      <td>51</td>
      <td>5</td>
      <td>11</td>
      <td>21</td>
      <td>57</td>
      <td>12</td>
      <td>6</td>
    </tr>
    <tr>
      <th>测试二</th>
      <td>66</td>
      <td>79</td>
      <td>66</td>
      <td>71</td>
      <td>4</td>
      <td>27</td>
      <td>98</td>
      <td>81</td>
      <td>55</td>
      <td>25</td>
      <td>60</td>
      <td>58</td>
    </tr>
    <tr>
      <th rowspan="2" valign="top">Chph</th>
      <th>测试一</th>
      <td>97</td>
      <td>72</td>
      <td>42</td>
      <td>66</td>
      <td>27</td>
      <td>66</td>
      <td>29</td>
      <td>88</td>
      <td>92</td>
      <td>77</td>
      <td>10</td>
      <td>70</td>
    </tr>
    <tr>
      <th>测试二</th>
      <td>17</td>
      <td>39</td>
      <td>70</td>
      <td>91</td>
      <td>77</td>
      <td>67</td>
      <td>30</td>
      <td>11</td>
      <td>80</td>
      <td>72</td>
      <td>35</td>
      <td>71</td>
    </tr>
    <tr>
      <th rowspan="2" valign="top">CCL</th>
      <th>测试一</th>
      <td>15</td>
      <td>29</td>
      <td>87</td>
      <td>1</td>
      <td>97</td>
      <td>64</td>
      <td>39</td>
      <td>42</td>
      <td>30</td>
      <td>32</td>
      <td>70</td>
      <td>64</td>
    </tr>
    <tr>
      <th>测试二</th>
      <td>74</td>
      <td>14</td>
      <td>1</td>
      <td>31</td>
      <td>15</td>
      <td>69</td>
      <td>20</td>
      <td>98</td>
      <td>72</td>
      <td>66</td>
      <td>45</td>
      <td>75</td>
    </tr>
    <tr>
      <th rowspan="8" valign="top">期末</th>
      <th rowspan="2" valign="top">Steve</th>
      <th>测试一</th>
      <td>85</td>
      <td>83</td>
      <td>52</td>
      <td>95</td>
      <td>83</td>
      <td>81</td>
      <td>52</td>
      <td>75</td>
      <td>26</td>
      <td>5</td>
      <td>51</td>
      <td>39</td>
    </tr>
    <tr>
      <th>测试二</th>
      <td>12</td>
      <td>0</td>
      <td>33</td>
      <td>25</td>
      <td>78</td>
      <td>88</td>
      <td>89</td>
      <td>16</td>
      <td>65</td>
      <td>78</td>
      <td>57</td>
      <td>23</td>
    </tr>
    <tr>
      <th rowspan="2" valign="top">Jobs</th>
      <th>测试一</th>
      <td>31</td>
      <td>67</td>
      <td>45</td>
      <td>35</td>
      <td>90</td>
      <td>4</td>
      <td>44</td>
      <td>62</td>
      <td>59</td>
      <td>39</td>
      <td>77</td>
      <td>48</td>
    </tr>
    <tr>
      <th>测试二</th>
      <td>16</td>
      <td>90</td>
      <td>99</td>
      <td>64</td>
      <td>88</td>
      <td>18</td>
      <td>5</td>
      <td>94</td>
      <td>96</td>
      <td>72</td>
      <td>22</td>
      <td>20</td>
    </tr>
    <tr>
      <th rowspan="2" valign="top">Chph</th>
      <th>测试一</th>
      <td>25</td>
      <td>86</td>
      <td>78</td>
      <td>31</td>
      <td>50</td>
      <td>15</td>
      <td>26</td>
      <td>47</td>
      <td>98</td>
      <td>38</td>
      <td>65</td>
      <td>0</td>
    </tr>
    <tr>
      <th>测试二</th>
      <td>48</td>
      <td>84</td>
      <td>93</td>
      <td>58</td>
      <td>5</td>
      <td>60</td>
      <td>60</td>
      <td>4</td>
      <td>91</td>
      <td>85</td>
      <td>32</td>
      <td>36</td>
    </tr>
    <tr>
      <th rowspan="2" valign="top">CCL</th>
      <th>测试一</th>
      <td>15</td>
      <td>42</td>
      <td>42</td>
      <td>62</td>
      <td>83</td>
      <td>36</td>
      <td>28</td>
      <td>13</td>
      <td>35</td>
      <td>24</td>
      <td>15</td>
      <td>16</td>
    </tr>
    <tr>
      <th>测试二</th>
      <td>40</td>
      <td>14</td>
      <td>23</td>
      <td>64</td>
      <td>61</td>
      <td>79</td>
      <td>14</td>
      <td>32</td>
      <td>86</td>
      <td>38</td>
      <td>23</td>
      <td>97</td>
    </tr>
  </tbody>
</table>
</div>

In [15]:
score['模拟考'][['语文','数学']]

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th></th>
      <th></th>
      <th>语文</th>
      <th>数学</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th rowspan="8" valign="top">期中</th>
      <th rowspan="2" valign="top">Steve</th>
      <th>测试一</th>
      <td>72</td>
      <td>76</td>
    </tr>
    <tr>
      <th>测试二</th>
      <td>82</td>
      <td>5</td>
    </tr>
    <tr>
      <th rowspan="2" valign="top">Jobs</th>
      <th>测试一</th>
      <td>80</td>
      <td>17</td>
    </tr>
    <tr>
      <th>测试二</th>
      <td>79</td>
      <td>66</td>
    </tr>
    <tr>
      <th rowspan="2" valign="top">Chph</th>
      <th>测试一</th>
      <td>72</td>
      <td>97</td>
    </tr>
    <tr>
      <th>测试二</th>
      <td>39</td>
      <td>17</td>
    </tr>
    <tr>
      <th rowspan="2" valign="top">CCL</th>
      <th>测试一</th>
      <td>29</td>
      <td>15</td>
    </tr>
    <tr>
      <th>测试二</th>
      <td>14</td>
      <td>74</td>
    </tr>
    <tr>
      <th rowspan="8" valign="top">期末</th>
      <th rowspan="2" valign="top">Steve</th>
      <th>测试一</th>
      <td>83</td>
      <td>85</td>
    </tr>
    <tr>
      <th>测试二</th>
      <td>0</td>
      <td>12</td>
    </tr>
    <tr>
      <th rowspan="2" valign="top">Jobs</th>
      <th>测试一</th>
      <td>67</td>
      <td>31</td>
    </tr>
    <tr>
      <th>测试二</th>
      <td>90</td>
      <td>16</td>
    </tr>
    <tr>
      <th rowspan="2" valign="top">Chph</th>
      <th>测试一</th>
      <td>86</td>
      <td>25</td>
    </tr>
    <tr>
      <th>测试二</th>
      <td>84</td>
      <td>48</td>
    </tr>
    <tr>
      <th rowspan="2" valign="top">CCL</th>
      <th>测试一</th>
      <td>42</td>
      <td>15</td>
    </tr>
    <tr>
      <th>测试二</th>
      <td>14</td>
      <td>40</td>
    </tr>
  </tbody>
</table>
</div>

In [16]:
score.loc['期中', '雷军', '测试一']['模拟考', '数学']

KeyError: 'the label [雷军] is not in the [columns]'

In [17]:
score.loc['期中', 'CCL', '测试一']['模拟考', '数学']

15

In [18]:
score.loc['期中', 'CCL', '测试一']

模拟考  数学    15
     语文    29
     英语    87
     物理     1
     化学    97
     生物    64
正式考  数学    39
     语文    42
     英语    30
     物理    32
     化学    70
     生物    64
Name: (期中, CCL, 测试一), dtype: int64

In [19]:
score.iloc[0]

模拟考  数学    76
     语文    72
     英语    51
     物理    73
     化学    22
     生物    78
正式考  数学    90
     语文    59
     英语    75
     物理     9
     化学    41
     生物    37
Name: (期中, Steve, 测试一), dtype: int64

In [20]:
score['正式考']

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th></th>
      <th></th>
      <th>数学</th>
      <th>语文</th>
      <th>英语</th>
      <th>物理</th>
      <th>化学</th>
      <th>生物</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th rowspan="8" valign="top">期中</th>
      <th rowspan="2" valign="top">Steve</th>
      <th>测试一</th>
      <td>90</td>
      <td>59</td>
      <td>75</td>
      <td>9</td>
      <td>41</td>
      <td>37</td>
    </tr>
    <tr>
      <th>测试二</th>
      <td>1</td>
      <td>37</td>
      <td>85</td>
      <td>34</td>
      <td>59</td>
      <td>33</td>
    </tr>
    <tr>
      <th rowspan="2" valign="top">Jobs</th>
      <th>测试一</th>
      <td>5</td>
      <td>11</td>
      <td>21</td>
      <td>57</td>
      <td>12</td>
      <td>6</td>
    </tr>
    <tr>
      <th>测试二</th>
      <td>98</td>
      <td>81</td>
      <td>55</td>
      <td>25</td>
      <td>60</td>
      <td>58</td>
    </tr>
    <tr>
      <th rowspan="2" valign="top">Chph</th>
      <th>测试一</th>
      <td>29</td>
      <td>88</td>
      <td>92</td>
      <td>77</td>
      <td>10</td>
      <td>70</td>
    </tr>
    <tr>
      <th>测试二</th>
      <td>30</td>
      <td>11</td>
      <td>80</td>
      <td>72</td>
      <td>35</td>
      <td>71</td>
    </tr>
    <tr>
      <th rowspan="2" valign="top">CCL</th>
      <th>测试一</th>
      <td>39</td>
      <td>42</td>
      <td>30</td>
      <td>32</td>
      <td>70</td>
      <td>64</td>
    </tr>
    <tr>
      <th>测试二</th>
      <td>20</td>
      <td>98</td>
      <td>72</td>
      <td>66</td>
      <td>45</td>
      <td>75</td>
    </tr>
    <tr>
      <th rowspan="8" valign="top">期末</th>
      <th rowspan="2" valign="top">Steve</th>
      <th>测试一</th>
      <td>52</td>
      <td>75</td>
      <td>26</td>
      <td>5</td>
      <td>51</td>
      <td>39</td>
    </tr>
    <tr>
      <th>测试二</th>
      <td>89</td>
      <td>16</td>
      <td>65</td>
      <td>78</td>
      <td>57</td>
      <td>23</td>
    </tr>
    <tr>
      <th rowspan="2" valign="top">Jobs</th>
      <th>测试一</th>
      <td>44</td>
      <td>62</td>
      <td>59</td>
      <td>39</td>
      <td>77</td>
      <td>48</td>
    </tr>
    <tr>
      <th>测试二</th>
      <td>5</td>
      <td>94</td>
      <td>96</td>
      <td>72</td>
      <td>22</td>
      <td>20</td>
    </tr>
    <tr>
      <th rowspan="2" valign="top">Chph</th>
      <th>测试一</th>
      <td>26</td>
      <td>47</td>
      <td>98</td>
      <td>38</td>
      <td>65</td>
      <td>0</td>
    </tr>
    <tr>
      <th>测试二</th>
      <td>60</td>
      <td>4</td>
      <td>91</td>
      <td>85</td>
      <td>32</td>
      <td>36</td>
    </tr>
    <tr>
      <th rowspan="2" valign="top">CCL</th>
      <th>测试一</th>
      <td>28</td>
      <td>13</td>
      <td>35</td>
      <td>24</td>
      <td>15</td>
      <td>16</td>
    </tr>
    <tr>
      <th>测试二</th>
      <td>14</td>
      <td>32</td>
      <td>86</td>
      <td>38</td>
      <td>23</td>
      <td>97</td>
    </tr>
  </tbody>
</table>
</div>

In [21]:
score['数学']

KeyError: '数学'

In [22]:
score['正式考','数学']

期中  Steve  测试一    90
           测试二     1
    Jobs   测试一     5
           测试二    98
    Chph   测试一    29
           测试二    30
    CCL    测试一    39
           测试二    20
期末  Steve  测试一    52
           测试二    89
    Jobs   测试一    44
           测试二     5
    Chph   测试一    26
           测试二    60
    CCL    测试一    28
           测试二    14
Name: (正式考, 数学), dtype: int64